version: "3"

services:
  web:
    restart: "always"
    build: .
    # environment:
    #   IP: 41.59.88.233
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    container_name: shulesoft_backup
    image: backup
    working_dir: /backup
    volumes:
      - .:/backup
      - /home/db_repository:/home/db_repository
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
      # - redis